### PR TITLE
[YesterdayWowrk] Added logic for adding stock - to be analyzed

### PR DESCRIPTION
**Pull request by tuganimana**
I have added yesterday work .. didn't finish it , I even asked how to handle it on  but got an answer that don't allow me to ask again.. so shared how I got it .. please review I will learn from that review..

### CODE REVIEW

**Review by richard457 — COMMENTED** [review]
This look as work in progress to me @tuganimana

**Comment by tuganimana** [comment]
Sure it's  Just wanted to share it as you said that I have to ask you when necessary.. I am not experienced in couchbase may be  based on what I did I can know what i did wrong .

**Comment by richard457** [comment]
Got it, This was 4 hours task, I will finish the work probably tonight so you can see how we did it. The knowledge of couchbase was not required in my opinion, there is an existing class for inserting and querying and examples in other places to relate to. The only problem I can see is the ability to collaborate and work in a team. @tuganimana

**Comment by tuganimana** [comment]
Ooh that's so! That's how you see it ?

**Comment by tuganimana** [comment]
It's fine let's call it that way!

**Pull request merged**
